In [110]:
import hoomd
import gsd.hoomd
import numpy as np


In [2]:
file=gsd.hoomd.open('test_2_init.gsd','w')
frame=gsd.hoomd.Frame()
frame.configuration.box=[10,10,10,0,0,0]
frame.particles.N=2
frame.particles.position=[[0,0,0],[0.5,0,0]]
frame.particles.type=['A']
frame.particles.typeid=[0]*2
file.append(frame)
file.close()

True

In [15]:
import gsd.hoomd
import numpy as np 
from polychrom.simulation import Simulation
import polychrom.starting_conformations
import polychrom.forces as forces
import polychrom.forcekits as forcekits
import polychrom.polymerutils

from polychrom.hdf5_format import HDF5Reporter
import matplotlib.pyplot as plt
import os

In [ ]:
monnum=[1000]
for i in monnum:
    positions=polychrom.starting_conformations.grow_cubic(i,50, method='standard')
    position=positions
    position=np.vstack((position,[0,0,21]))
    print(len(position))
    ptclid=np.zeros(len(position))
    ptclid[4000]=2
    bonds=[]
    bdid=[]
    for j in range(i) :
        if j<i-1:
            bonds.append([j,j+1])
            
        if j==i-1:
            bonds.append([0,j])
        bdid.append([0])    
    bonds.append([0,4000])   
    bdid.append([2])     
    frame=gsd.hoomd.Frame()
    frame.configuration.box=[100,100,100,0,0,0]
    frame.particles.N=i+1
    frame.particles.position=position
    frame.particles.types=['A','ParB','teather']
    frame.particles.typeid=ptclid
    frame.bonds.N=len(bonds)
    frame.bonds.group=bonds
    frame.bonds.types=['A-A','crosslink','teatheredbond']
    frame.bonds.typeid=bdid
    
    os.makedirs('initfiles',exist_ok=True)
    file=gsd.hoomd.open(f'initfiles/init_{i}_poly.gsd',mode='w')
    file.append(frame)
    file.close()

INFO:gsd.fl:overwriting file: initfiles/init_4000_poly.gsd with mode: w, application: gsd.hoomd 3.3.0, schema: hoomd, and schema_version: [1, 4]
INFO:gsd.hoomd:opening HOOMDTrajectory: <gsd.fl.GSDFile object at 0x5644fada6a70>
INFO:gsd.hoomd:found 0 frames
INFO:gsd.fl:closing file: initfiles/init_4000_poly.gsd


4001


In [111]:
import numpy as np

def cartesian_to_cylindrical(x, y, z):
    r = np.sqrt(x**2 + y**2)       # Radial distance
    theta = np.arctan2(y, x)       # Azimuthal angle in radians
    return r, theta, z

def cylindrical_to_cartesian(r,theta,z):
    x=r*np.cos(theta)
    y=r*np.sin(theta)
    z=z
    return x,y,z

def cartesian_to_spherical(x,y,z):
    r=np.sqrt(x**2+y**2+z**2)
    theta = np.arctan2(y, x)     
    phi = np.arccos(z / r) 
    return r,theta,phi

def spherica_to_cartesian(r,theta,phi):
    x=r*np.sin(theta)*np.cos(phi)
    y=r*np.sin(theta)*np.sin(phi)
    z=r*np.cos(theta)
    return x,y,z

In [31]:
pos=np.zeros((1001,3))
ptclid=np.zeros(len(position))
pos[1000]=[0,0,12.5]
ptclid[1000]=2
for i in range(0,1000):
    while True:
        randtheta=2*np.pi*np.random.random()
        randphi=np.pi*np.random.random()
        x1,y1,z1=spherica_to_cartesian(1,randtheta,randphi)
        pos[i]=pos[i-1]+np.array([x1,y1,z1])
        r1=np.sqrt(pos[i][0]**2+pos[i][1]**2)
        # print(r1,z1)
        zpos=pos[i][2]
        if(r1>3 or zpos>12.5 or zpos<-12.5):
            print(i)
            continue

        else:
            pos[i]=pos[i-1]+np.array([x1,y1,z1])
            break
len(pos)

0
20
21
30
32
32
35
35
37
39
39
55
69
85
95
104
145
145
154
155
156
161
188
189
211
211
211
212
216
216
216
216
216
220
221
222
224
227
227
227
233
244
248
251
260
260
260
261
265
270
279
304
306
311
313
316
329
329
329
371
376
377
377
377
377
379
380
380
391
398
406
413
413
413
413
416
416
416
416
420
432
432
434
434
434
435
436
441
441
444
454
454
466
467
468
468
472
474
488
489
490
495
495
500
544
546
558
562
562
567
569
572
578
578
578
579
579
579
579
579
579
579
580
580
584
584
588
601
605
638
678
680
680
681
681
686
689
689
691
694
697
697
697
700
700
710
716
723
723
741
741
757
769
802
804
816
816
817
820
820
823
831
831
832
832
850
851
853
866
866
866
866
866
876
877
913
914
914
915
917
917
922
923
926
927
927
962
964
965
966
971
973
976
976
983
988
988
990
994


1001

In [32]:
position=pos
print(len(position))
# ptclid=np.zeros(len(position))
bonds=[]
bdid=[]
i=1000 
for j in range(i) :
    if j<i-1:
        bonds.append([j,j+1])
        
    if j==i-1:
        bonds.append([0,j])
    bdid.append([0])    
bonds.append([0,1000])   
bdid.append([2])     
frame=gsd.hoomd.Frame()
frame.configuration.box=[100,100,100,0,0,0]
frame.particles.N=i+1
frame.particles.position=position
frame.particles.types=['A','ParB','teather']
frame.particles.typeid=ptclid
frame.bonds.N=len(bonds)
frame.bonds.group=bonds
frame.bonds.types=['A-A','crosslink','teatheredbond']
frame.bonds.typeid=bdid

os.makedirs('initfiles',exist_ok=True)
file=gsd.hoomd.open(f'initfiles/init_{i}_poly.gsd',mode='w')
file.append(frame)
file.close()

INFO:gsd.fl:overwriting file: initfiles/init_1000_poly.gsd with mode: w, application: gsd.hoomd 3.3.0, schema: hoomd, and schema_version: [1, 4]
INFO:gsd.hoomd:opening HOOMDTrajectory: <gsd.fl.GSDFile object at 0x55cca1a9bbf0>
INFO:gsd.hoomd:found 0 frames
INFO:gsd.fl:closing file: initfiles/init_1000_poly.gsd


1001


In [60]:
a=-1.46373+1.6502
b=-0.171149+1.76629
c=13.7709-12.1526
cartesian_to_spherical(a,b,c)

(2.2799431485852883, 1.454425732375647, 0.7815843571239431)

In [62]:
snapshot=gsd.hoomd.open('initfiles/equiled1_4000_poly.gsd','r')
snapshot=snapshot[0]

INFO:gsd.fl:opening file: initfiles/equiled1_4000_poly.gsd with mode: r
INFO:gsd.hoomd:opening HOOMDTrajectory: <gsd.fl.GSDFile object at 0x56124f20eae0>
INFO:gsd.hoomd:found 1 frames
INFO:gsd.fl:closing file: initfiles/equiled1_4000_poly.gsd
INFO:gsd.fl:closing file: initfiles/equiled1_4000_poly.gsd


In [3]:
initframe=gsd.hoomd.open('initfiles/equiled3_4000_poly.gsd',mode='r')

In [4]:
frame=gsd.hoomd.Frame()
frame=initframe[0]
frame.configuration.box=[30,30,100,0,0,0]
particleid=frame.particles.typeid
frame.particles.types

['A', 'ParB', 'teather']

In [5]:

positions=frame.particles.position
N=len(positions)
compartment=[[],[],[],[],[],[],[],[]]
for i in range(N):
    pos=positions[i][2]
    index=(pos+21.5)//5
    if index<=7:
        compartment[int(index)].append(i)
    



In [6]:
for num in range(8):
    parnum=40-num*5
    randomindex= np.random.choice(compartment[num], size=parnum, replace=False)
    for index in randomindex:
        particleid[index]=3
for j in range(10):
    particleid[j]=1
    particleid[4000-(j+1)]=1
    
frame.particles.typeid=particleid
frame.particles.types=['A','ParB','teather','ParA','replisome','D2']

newfile=gsd.hoomd.open('initfiles/equiled_ParAB_4000_poly.gsd','w')
newfile.append(frame)
newfile.close()

TypeError: 'Loggable' object is not subscriptable

In [12]:
from gsd.hoomd import *
from numpy import *


file=open('Ccrescentusequiled.gsd','r')

ptypeid=file[0].particles.typeid
ptype=['A','ParB','teather','ParA','replisome','D2']

ptypePara=where(ptypeid==5)[0]

ptypeid=zeros(501)

for i in ptypePara:
    ptypeid[i]=3

for i in range(2):
    ptypeid[i]=1
    ptypeid[499-i]=1
ptypeid[500]=2
btypeid=file[0].bonds.typeid
len(btypeid)

503

In [7]:

frame=Frame()
frame=file[0]
frame.configuration.box=[9,9,40,0,0,0]
frame.particles.typeid=ptypeid
frame.particles.types=ptype
frame.bonds.N=501
frame.bonds.typeid=[0]*501
frame.bonds.group=file[0].bonds.group[:501]
frame.bonds.types=['A-A','crosslink','teatheredbond']

newfile=open('initfiles/equiled3_500_poly.gsd','w')
newfile.append(frame)

newfile.close()



In [79]:
initframe=gsd.hoomd.open('initfiles/Newinit1000_28_4_new.gsd',mode='r')
frame=gsd.hoomd.Frame()
frame=initframe[0]
particleid=frame.particles.typeid
particleid[:1000]=0
particleid[1001]=6
bgroup=np.copy(initframe[0].bonds.group[:1001])
bgroup=np.vstack((initframe[0].bonds.group[1001:],initframe[0].bonds.group[:1001]))
btypeid=np.copy(initframe[0].bonds.typeid)
ptype=['A','ParB','teather1','ParA','replisome','D2','teather2']
frame.particles.types=ptype
# len(particleid)

# btypeid[500]=1


In [ ]:
positions=frame.particles.position
# positions[1000]=[0,0,13]

l=28
N=len(positions[:1000])

compartment=[[],[],[],[],[],[],[],[],[]]
for i in range(N):
    pos=positions[i][2]
    # positions[i][2]=positions[i][2]+l/2
    index=np.int((pos)/2.5)

    if index<=10:
        compartment[int(index)].append(i)

compartment[0]

/tmp/ipykernel_4016573/2604028684.py:11: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  index=np.int((pos)/2.5)


[428,
 429,
 430,
 431,
 432,
 433,
 434,
 435,
 436,
 437,
 438,
 449,
 450,
 451,
 452,
 453,
 454,
 456,
 457,
 475,
 476,
 477,
 478,
 479,
 480,
 481,
 482,
 483,
 484,
 485,
 486,
 504,
 505,
 506,
 507,
 508,
 509,
 510,
 511,
 512,
 513,
 514,
 515,
 516,
 517,
 518,
 519,
 520,
 521,
 522,
 523,
 524,
 525,
 526,
 527,
 528,
 529,
 530,
 531,
 532,
 533,
 534,
 535,
 536,
 537,
 538,
 539,
 540,
 541,
 542,
 545,
 546,
 547,
 548,
 549,
 550,
 551]

In [85]:
sum=0
for i in range(9):        
    print(f'number of particles in {i} th comp:{len(compartment[i])}')
    sum=sum+len(compartment[i])

sum/9


number of particles in 0 th comp:77
number of particles in 1 th comp:90
number of particles in 2 th comp:99
number of particles in 3 th comp:94
number of particles in 4 th comp:97
number of particles in 5 th comp:99
number of particles in 6 th comp:93
number of particles in 7 th comp:105
number of particles in 8 th comp:72


91.77777777777777

In [ ]:
import numpy as np
decay_const=2.56
max_particles=48



for num in range(11):
    # parnum=8-num*1
    parnum = int(np.exp(-num / decay_const) * max_particles)
    randomindex= np.random.choice(compartment[num], size=parnum, replace=False)
    for index in randomindex:
        particleid[index]=3
for j in range(2):
    particleid[j]=1
    particleid[1000-(j+1)]=1
frame.particles.position=positions    
frame.particles.typeid=particleid
frame.bonds.typeid=btypeid
frame.bonds.group=bgroup
frame.configuration.box=[20,20,70,0,0,0]
newfile=gsd.hoomd.open('initfiles/equiled_ParAB_1000_28_4_140_new.gsd','w')
newfile.append(frame)
newfile.close()

In [48]:
initframe=gsd.hoomd.open('initfiles/equiled_ParAB_4000_poly.gsd',mode='r')
frame=gsd.hoomd.Frame()
frame=initframe[0]
particleid=frame.particles.typeid
particleid[:4000]=0
btypeid=np.copy(initframe[0].bonds.typeid)
frame.particles.types
len(particleid)

4001

In [49]:
positions=frame.particles.position
# positions[500]=[0,0,10]
for i in range(len(positions)):
    positions[i][2]=positions[i][2]+42.5/2
l=42.5
N=len(positions)
compartment=[[],[],[],[],[],[],[],[],[],[]]
for i in range(N):
    pos=positions[i][2]
    index=(pos)//4
    if index<=9:
        compartment[int(index)].append(i)

In [ ]:
decay_const=3.25
max_particles=24
for num in range(10):
    # parnum=8-num*1
    parnum = int(np.exp(-num / decay_const) * max_particles)
    randomindex= np.random.choice(compartment[num], size=parnum, replace=False)
    for index in randomindex:
        particleid[index]=3
    print (parnum)
for j in range(9):
    particleid[j]=1
    particleid[4000-(j+1)]=1
frame.particles.position=positions    
frame.particles.typeid=particleid
frame.bonds.typeid=btypeid
frame.configuration.box=[20,20,100,0,0,0]
newfile=gsd.hoomd.open('initfiles/equiled_ParAB_4000_42.5_poly_assym_185.gsd','w')
newfile.append(frame)
newfile.close()

15
11
8
5
4
3
2
1
1


IndexError: list index out of range

In [2]:

import numpy as np
decay_const=2.59
max_particles=34




sum=0
for num in range(11):
    parnum = int(np.exp(-num / decay_const) * max_particles)
    print (parnum)
    sum=sum+parnum

print(sum)

34
23
15
10
7
4
3
2
1
1
0
100


In [157]:
oldinit=gsd.hoomd.open('initfiles/Newinit1000_28_4.gsd',mode='r')

In [158]:
frame=gsd.hoomd.Frame()
# frame=oldinit[0]

bonds=oldinit[0].bonds.group[:1001]
btypeid=oldinit[0].bonds.typeid[:1001]
crosslinks=[[166,832],[333,666]]
bonds=np.vstack((bonds,crosslinks))
btypeid=np.append(btypeid,[1,1])

pos=oldinit[0].particles.position[:1001]
ptype=oldinit[0].particles.typeid[:1001]
orient=oldinit[0].particles.orientation

pos=np.vstack((pos,np.array([0,0,1])))
# vel=np.vstack((vel,np.array([0,0,0])))
ptype=np.append(ptype,[2])

In [159]:

frame.configuration.box=oldinit[0].configuration.box
frame.bonds.N=len(bonds)
frame.bonds.types=oldinit[0].bonds.types
frame.bonds.group=bonds
frame.bonds.typeid=btypeid
frame.particles.position = pos
frame.particles.typeid = ptype
frame.particles.types= oldinit[0].particles.types
frame.particles.N = len(pos)
# frame.particles.velocity=vel
len(pos)

1002

In [160]:
newinit=gsd.hoomd.open('initfiles/Newinit1000_28_4_1.gsd',mode='w')
newinit.append(frame)
newinit.close()

In [ ]:
def exp_dist(self,x,rho):
            norm=1/(rho*(1-np.exp(-11/rho)))
            func=norm*np.exp(-x/rho)
            return func,norm


In [12]:
rho=100
norm=1/(rho*(1-np.exp(-11/rho)))
norm

0.0960007390949706

In [15]:
import gsd.hoomd
import numpy as np
file= gsd.hoomd.open(f'1000monruns/100ParA/expo/A5soft_20k_8.50_fullring_1000_100_28_4_10krate_assym_popz/run_0_20k_3.50_fullringrepsoft.gsd',mode='r')

frame=file[15]
bonds=frame.bonds.group
bdid=frame.bonds.typeid
position=frame.particles.position
ptclid=frame.particles.typeid


delbonds=[[1004,3],[1005,996],[1002,1004],[1003,1005]]
delptcl=[1004,1004]


print(len(bonds))
for bds in delbonds:
    ids=np.where((bonds==bds).all(axis=1))[0][0]
    print(ids)
    bonds = np.delete(bonds, ids, axis=0)
    bdid=np.delete(bdid, ids, axis=0)
print(len(bonds)) 

print('before:',len(position))
for ptcl in delptcl:
    position=np.delete(position,ptcl,axis=0)
    ptclid=np.delete(ptclid,ptcl,axis=0)

print('after:',len(position))

print(bonds[-1],position[-2:])
bonds[-1]=[0,1004]
newinit=gsd.hoomd.open('1000monruns/100ParA/expo/Newinit1000_ParB_testenergetics.gsd',mode='w')
newframe = gsd.hoomd.Frame()

newframe.configuration.box = frame.configuration.box

newframe.particles.N = len(position)
newframe.particles.position = position
newframe.particles.typeid = ptclid
newframe.particles.types = frame.particles.types

newframe.bonds.N = len(bonds)
newframe.bonds.group = bonds
newframe.bonds.typeid = bdid
newframe.bonds.types = frame.bonds.types

newinit.append(newframe)
# newinit.append(frame)

newinit.close()

1008
1005
1005
1003
1003
1004
before: 1008
after: 1006
[   0 1006] [[ 0.         0.        27.       ]
 [ 0.         0.         0.9222598]]


In [31]:
import gsd.hoomd
import numpy as np
file= gsd.hoomd.open(f'1000monruns/100ParA/expo/A5soft_20k_8.50_fullring_1000_100_28_4_10krate_assym_popz/run_103_20k_3.50_fullringrepsoft.gsd',mode='r')
framenumb=80*20
frame=file[framenumb]
bonds=frame.bonds.group
bdid=frame.bonds.typeid
position=frame.particles.position
ptclid=frame.particles.typeid

newinit=gsd.hoomd.open('1000monruns/100ParA/expo/Newinit1000_ParB_80%Rep.gsd',mode='w')
position

array([[ -0.16404925,  -0.6914246 ,  26.029991  ],
       [ -0.54802954,   0.12106651,  25.59864   ],
       [ -1.0165797 ,   0.8630742 ,  26.2663    ],
       ...,
       [ -1.5674598 ,   1.622371  ,  11.081512  ],
       [  0.        ,   0.        ,  27.        ],
       [  0.        ,   0.        , -19.683296  ]], dtype=float32)

In [32]:

k=np.log(2)/(500)
z1=28*np.exp(400*k)
dx=(28-z1/2)
for i in range(len(position)):
    position[i][2]=position[i][2]-dx
position

array([[ -0.16404925,  -0.6914246 ,  22.405407  ],
       [ -0.54802954,   0.12106651,  21.974056  ],
       [ -1.0165797 ,   0.8630742 ,  22.641716  ],
       ...,
       [ -1.5674598 ,   1.622371  ,   7.4569283 ],
       [  0.        ,   0.        ,  23.375416  ],
       [  0.        ,   0.        , -23.30788   ]], dtype=float32)

In [33]:
changeid=np.where((ptclid==4))
print(changeid)
for i in changeid[0]:
    ptclid[i]=5
ptclid[400]=4
ptclid[599]=4

(array([1798, 1799]),)


In [34]:
newframe = gsd.hoomd.Frame()

newframe.configuration.box = [70,70,70,0,0,0]

newframe.particles.N = len(position)
newframe.particles.position = position
newframe.particles.typeid = ptclid
newframe.particles.types = frame.particles.types

newframe.bonds.N = len(bonds)
newframe.bonds.group = bonds
newframe.bonds.typeid = bdid
newframe.bonds.types = frame.bonds.types

newinit.append(newframe)
# newinit.append(frame)

newinit.close()

In [4]:
import gsd.hoomd
import numpy as np
fl=gsd.hoomd.open(name='1000monruns/100ParA/expo/A5soft_8.50_100_4_10krate_assym_popz_30%rep/run_1_20k_3.50_fullringrepsoft.gsd',mode='r')

In [5]:
len(fl)

524293

In [14]:
import gsd.hoomd
import numpy as np
fl=gsd.hoomd.open(name='initfiles/equiled_1000_28_4_crosslinked1.gsd',mode='r')

newinit=gsd.hoomd.open(name='initfiles/equiled_1000_28_4_crosslinked2.gsd',mode='w')

In [15]:
groups=fl[0].bonds.group[2:]
bdid=fl[0].bonds.typeid[2:]
position=fl[0].particles.position
ptclid=fl[0].particles.typeid
fl[0].particles.types,ptclid



(['A', 'ParB', 'teather1', 'ParA', 'replisome', 'D2', 'teather2'],
 array([1, 1, 0, ..., 1, 2, 6], dtype=uint32))

In [16]:
import numpy as np

newbonds=[[250,749],[625,374]]
newtypeid=[1,1]

bgroup=np.vstack((np.array(newbonds),groups))
bdid=np.append(np.array(newtypeid),bdid)
len(bgroup),len(bdid)

(1003, 1003)

In [18]:
newframe = gsd.hoomd.Frame()

newframe.configuration.box = [70,70,60,0,0,0]

newframe.particles.N = len(position)
newframe.particles.position = position
newframe.particles.typeid = ptclid
newframe.particles.types = fl[0].particles.types

newframe.bonds.N = len(bgroup)
newframe.bonds.group = bgroup
newframe.bonds.typeid = bdid
newframe.bonds.types = fl[0].bonds.types

newinit.append(newframe)
# newinit.append(frame)

newinit.close()